spring.application.name=journal App

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
#spring.data.mongodb.user.name =
#spring.data.mongodb.user.password =

#SPRING BOOT ACTUATOR CONFIGS
management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/manage
info.app.name=My Spring Boot App
info.app.description=Demo application
info.app.version=1.0.0